name: Build Hyprland

on: [push, pull_request, workflow_dispatch]
jobs:
  gcc:
    name: "Build Hyprland (Arch)"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Checkout repository actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions

      - name: Setup base
        uses: ./.github/actions/setup_base
        with:
          INSTALL_XORG_PKGS: true

      - name: Build Hyprland
        run: |
          make all
      - name: Compress and package artifacts
        run: |
        pacman -Syuu
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: Build archive
          path: Hyprland.tar.xz
